### ISSUE TITLE
IOError: [Errno 11] Resource temporarily unavailable

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/Documentation#1]
Getting this error while using adduser.py and renewuser.py.

```
Traceback (most recent call last):
  File "./renewuser.py", line 236, in <module>
    export_group.run()
  File "/home/u/upl/bin/export_group.py", line 20, in run
    group_file = open(os.path.join(config.ExportDir, 'group.upl'),"w")
IOError: [Errno 11] Resource temporarily unavailable: '/home/a/adm/etc/export/group.upl'
```

**Comment by WowSuchRicky** [comment]
Temp fix (if you get a failure upon adding user):

-create home folder for the user (/home/<first letter of username>/<full username>)
-run renewuser.py on their user
-chown their home folder to their user
-done

**Comment by LOZORD** [comment]
Yup, just this part [here](https://github.com/UW-UPL/Documentation#adding-user). We should add some handling for this problem though.

**Comment by daguava** [comment]
Hard to add problem handling when we don't know the cause and don't know a reliable fix, I've had it fail similarly several times in a row.

**Comment by LOZORD** [comment]
I will look at this issue on Friday (please remind me :wink: )

**Comment by LOZORD** [comment]
I took a look at the contents of `export_group.py` and there seems to be a few hacks and a lot of cruft. It may be simplest just to remove unnec. lines from this file to fix the issue. @Ricky54326 what do you think?

**Comment by LOZORD** [comment]
I'm suspicious from running `grep "group.upl" . -rnI --color` and seeing multiple occurrences. Does this smell like a race condition to anyone?

**Comment by daguava** [comment]
No, because when these errors happen you can sometimes try to open the file with something like nano and nano will have the error too.
Also this never happened on old server installation for some reason.

**Comment by LOZORD** [comment]
As much as I like dealing with arcane file IO race conditions, @jdetter 's improved `add-user` script should make this issue a moot point. This can be closed when that script is good to go.

**Comment by jdetter** [comment]
The new user script is looking really good, I will finish it today for sure. It will also be super easy for us to make a remove user script, so I can probably do that for us today as well.
