### ISSUE TITLE
Create Markdown Version of New User Form

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/Documentation#10]
Should have equivalent content to [the current PDF](https://gist.github.com/LOZORD/9d23396e4206a5b1cb02). Should be convertable to a PDF.

**Comment by katamaritaco** [comment]
Waiting on https://github.com/UW-UPL/Documentation/issues/15 and then finished.

**Comment by WowSuchRicky** [comment]
This is done now, no? If not, re-open.
