### ISSUE TITLE
After conversion of all files to .md, place them in an archived folder.

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/Documentation#13]
Files that need to be converted:
Add_UPL_User.docx - DONE
UPL_Svcs_and_Commands - DONE
newuser.pdf (new user sign up)

**Comment by katamaritaco** [comment]
Waiting on: https://github.com/UW-UPL/Documentation/issues/15

**Comment by katamaritaco** [comment]
#15 is done. Just need to move old files into an archived folder in this repo now

**Comment by LOZORD** [comment]
@katamaritaco what needs to be done to close this?

**Comment by katamaritaco** [comment]
"#15 is done. Just need to move old files into an archived folder in this repo now"
