### ISSUE TITLE
Add new account policy to new user forms.

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/Documentation#15]
Waiting on solidifying the account policy before doing this

**Comment by katamaritaco** [comment]
related to https://github.com/UW-UPL/Documentation/issues/12

**Comment by LOZORD** [comment]
Could we just have the old link point or redirect to the new one?

**Comment by katamaritaco** [comment]
I'm not a fan of putting a link of the paper. The policy is simple enough that it can just go on the form. Although if more people think a link is sufficient, then so be it.

**Comment by LOZORD** [comment]
If you can fit it, I'd be fine with that.

**Comment by WowSuchRicky** [comment]
This is done, but also needs to be changed around on the website too per @melutzke

**Comment by daguava** [comment]
overall, it prob wouldn't be done until the new new user forms are made and the policy is printed on it :^)

**Comment by katamaritaco** [comment]
I just added a link to the github of the CoC. Should be fine, since no way CoC would fit on NuN form. It is big now.
