### ISSUE TITLE
Make ~upl/ a github repo

### ISSUE THREAD

**Issue by daguava** [UW-UPL/Documentation#16]
^^^

**Comment by LOZORD** [comment]
Are we sure that we want to do this? What is the motivation?

**Comment by daguava** [comment]
Do you know what's in ~upl/ ? If not, I'd encourage you to look around and investigate. It should be overwhelmingly obvious why it should be in source control.

**Comment by LOZORD** [comment]
But in public, or with a local/private git?

**Comment by daguava** [comment]
Private, with all coords added to repo.

**Comment by LOZORD** [comment]
Ok, yeah that sounds good.

**Comment by daguava** [comment]
https://github.com/UW-UPL/UPL-Config

Added most important folders, and a lot that likely contain old crap / cruft.

This can definitely be significantly pruned down, but I'd rather start with too much than too little.
