### ISSUE TITLE
Website Repository

### ISSUE THREAD

**Issue by daguava** [UW-UPL/Documentation#19]
Add current website to a new repository, and commit it so it is cataloged and preserved.

Then you can start building the new site in a new branch, or something to that effect.

Ideally, this means old resources are preserved in case things are needed in the future.

This should be a private repository, just in-case-sies, there's got to be sensitive stuff somewhere in the code of the current site (such as the hardcoded password for kb)

**Comment by mjneil** [comment]
Where is the current website stored? Documentation says Spearow handles the web server and such, but I cant find it.

**Comment by daguava** [comment]
(I'm withholding info on purpose) There's probably a config file for whatever software serves the website (apache or nginx) you can check that will give you the document root.

**Comment by mjneil** [comment]
Thoughts on just not putting the current website on github at all?  End goal I would like the upl website to be public open source, and the current site has a lot of sensitive information. It would be such a hassle to go through and remove it or selectively .ignore it

**Comment by daguava** [comment]
Up to you, I'm graduating :^)

I would make and keep around a backup of old site just in case you ever need to dig anything out of it. (files and mysql db)

**Comment by LOZORD** [comment]
Yeah, I don't think the old site _needs_ to be on GitHub, but I definitely agree that we should archive it somehow.

**Comment by katamaritaco** [comment]
I'd suggest creating an 'archive' repository where we dump old/inactive projects.

**Comment by LOZORD** [comment]
Yeah, that sounds alright as long as we keep it somewhat organized and not too much of a trash dump.

**Comment by WowSuchRicky** [comment]
This is definitely done, see https://github.com/UW-UPL/uw-upl.github.io
