### ISSUE TITLE
Create addcoord (and remove coord) scripts

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/Documentation#2]
We should create a wrapper script for adding coords. Could just be a branch of the adduser script.

**Comment by katamaritaco** [comment]
Should we also add these scripts on github. Either here or coord page?

**Comment by LOZORD** [comment]
I think we should make it private if possible, unless we are REALLY sure about what we are doing.

**Comment by LOZORD** [comment]
@jdetter is this complete?

**Comment by jdetter** [comment]
This is complete -- the coord must already exist as a user for my script to work though (which shouldn't be an issue).
