### ISSUE TITLE
Exporting groups (export_group.py) ALWAYS takes two tries, failing from an Errno 11 IOError.

### ISSUE THREAD

**Issue by WowSuchRicky** [UW-UPL/Documentation#20]
`root@eris:/home/u/upl/bin# python export_group.py
Traceback (most recent call last):
  File "export_group.py", line 75, in <module>
    run()
  File "export_group.py", line 20, in run
    group_file = open(os.path.join(config.ExportDir, 'group.upl'),"w")
IOError: [Errno 11] Resource temporarily unavailable: '/home/a/adm/etc/export/group.upl'`

`root@eris:/home/u/upl/bin# python export_group.py
/home/a/adm/etc/export/group.upl`

`root@eris:/home/u/upl/bin#`

**Comment by WowSuchRicky** [comment]
This is related to #1  but in a different setting.

**Comment by daguava** [comment]
On a hunch, did a bit of googling around AFS/NFS and locks with the "resource temporarily unavailable" message, and it seems we're getting bit by stale file locks getting left open.

No idea the cause, but this is hopefully a step in the direction of solving it.

**Comment by WowSuchRicky** [comment]
Gonna look at this again soon.

**Comment by WowSuchRicky** [comment]
This may be fixed by our AFS migration...... stay tuned I guess

**Comment by LOZORD** [comment]
Also having a non-janky `add_user` script :disappointed:

**Comment by jdetter** [comment]
Can this be closed? Add user script is working perfectly

**Comment by WowSuchRicky** [comment]
yep, works for me! thanks again for all of your hard work on this @jdetter

**Comment by jdetter** [comment]
No problem!!
