### ISSUE TITLE
Switch to a "sudoers file" type approach instead of a janky ass PSQL database

### ISSUE THREAD

**Issue by WowSuchRicky** [UW-UPL/Documentation#23]
Can we explore this possiblity?

**Comment by LOZORD** [comment]
Yeah, this seems like a good option. Very "idiot-proof" and easy :smiley: 
I'm curious about
- migration _from_ postgres
- implications for CSL
- security

**Comment by daguava** [comment]
the PSQL db is used for more than the sudoers file, it also is used for generation of shadow and passwd files, and ties in to some of the weird files we pull from the CSL so we know who we can make accounts for (as Leo mentioned).

Anyone who is willing to definitively take care of this would need to do the following:
1) Go through the python scripts and see what tables they all use
2) View the tables, see what they store
3) Start decoupling chunks from the postgres db

Ideally, nothing we do needs to use a postgres db, we're small enough that flat files would be fine, and we really don't store anything too sensitive in the DB anyhow.

**Comment by LOZORD** [comment]
@jdetter it sound like you fixed this?

**Comment by jdetter** [comment]
This is done, all coords are added to a group called 'sudo' on the workstations. I still have to configure the servers

**Comment by WowSuchRicky** [comment]
thank you based @jdetter
