### ISSUE TITLE
Create policy regarding rotation of root password

### ISSUE THREAD

**Issue by daguava** [UW-UPL/Documentation#25]
Ideally it shouldn't be the same forever. Current pass is from the Swarthout days.

**Comment by katamaritaco** [comment]
Yup - definitely same password for at least 5 years. Should we choose one at starting meeting of the semester, along with possibly getting passwordmaanger repo set up? @Ricky54326

**Comment by daguava** [comment]
When the password is changed, cfengine2 provides some functionality for running commands on all machines at the same time, might be helpful to use this to change all machine root passwords in one go.

**Comment by WowSuchRicky** [comment]
https://github.com/UW-UPL/DatSecurity
