### ISSUE TITLE
Fix the screwdriver problem with Siren

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/Documentation#26]
We should not need to do this -- @katamaritaco

**Comment by daguava** [comment]
Needs a two-pin wire extension, something that someone can do by themselves with some wire, or prob a $1 from mammyzhone.

**Comment by daguava** [comment]
http://www.newegg.com/Product/Product.aspx?Item=9SIA85V3DG9644&cm_re=front_panel_cable_extension-_-9SIA85V3DG9644-_-Product

there's probably much cheaper options, but this is the first I found

**Comment by katamaritaco** [comment]
@jdetter said this was fixed
