### ISSUE TITLE
Catalog status of machines & equiptment

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/Documentation#28]

**Comment by katamaritaco** [comment]
Can place in here: https://github.com/UW-UPL/Equipment

**Comment by LOZORD** [comment]
@bhans117 what needs to be done to close this?

**Comment by katamaritaco** [comment]
@bhans117 has been going ham... Are you basically finished?

**Comment by katamaritaco** [comment]
bump @bhans117

**Comment by bhans117** [comment]
I would like to touch some of this up, but that comes more when we get the new computers. So for right now, I will be closing this particular issue and open a new one when the new machines come in.

**Comment by bhans117** [comment]
I would like to touch some of this up, but that comes more when we get the new computers. So for right now, I will be closing this particular issue and open a new one when the new machines come in.
