### ISSUE TITLE
Add list of machines available with their names in order to ssh in

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/Documentation#29]
Add this list to the readme. Would be nice to have a list handy

**Comment by LOZORD** [comment]
@Squeakrats did you do something like this for the website?

**Comment by katamaritaco** [comment]
Yes it is in lab status page

Get Outlook for Androidhttp://aka.ms/ghei36

On Mon, Feb 8, 2016 at 12:24 PM -0800, "Leo Rudberg" <notifications@github.com<mailto:notifications@github.com>> wrote:

@Squeakratshttps://github.com/Squeakrats did you do something like this for the website?

##

**Comment by katamaritaco** [comment]
This is in the new lab status page on the new website. Closing
