### ISSUE TITLE
Come up with way to have people ask to be invited to slack channel

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/Documentation#30]
This should preferably go on new website as a little form or whatnot.

**Comment by LOZORD** [comment]
Maybe have a link to the channel and/or say that they should email `upl-coords`?

**Comment by katamaritaco** [comment]
A link on the website and facebook page?

I think too, there is a way to set up a tiny page that just reads in emails and auto invites. I've seen that for some channels...

**Comment by LOZORD** [comment]
See https://github.com/UW-UPL/uw-upl.github.io/issues/51

**Comment by katamaritaco** [comment]
closing because Leon hasn't updated, and we it is issue for website (possibly not issue at all, we'll see :camel: )

**Comment by LOZORD** [comment]
CLOSE THIS ISSUE ALREADY :trollface:
