### ISSUE TITLE
Account Management for UPL Accounts

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/Documentation#31]
We need to have a better way of managing UPL accounts on third party sites. For example, we have a Youtube, Facebook, Gmail, and Slack account. These should be consolidated and info distributed amongst coords.

**Comment by LOZORD** [comment]
A lot of this has to do with how we are going to maintain our passwords.

**Comment by katamaritaco** [comment]
Yup it is already listed as such on the gdoc for UPL H A C K but put here for severity/emphasis

**Comment by katamaritaco** [comment]
Check this:
https://github.com/UW-UPL/DatSecurity/blob/master/README.md

**Comment by LOZORD** [comment]
@katamaritaco can we close this issue yet? :smirk_cat:

**Comment by katamaritaco** [comment]
Yeah that repo is going to essentially fix these issues
