### ISSUE TITLE
Create a document for 'Coord Responsibilities'

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/Documentation#32]
Would be nice to have a reference to refer to. Solidify duties and such.

Keep the Lab Open.
1 Hour a week
Maintain lab
etc.

**Comment by katamaritaco** [comment]
working on it now:

https://github.com/UW-UPL/Documentation/blob/master/Coordinator-Responsibilities.md

**Comment by LOZORD** [comment]
Things to add(?):
- 1 event per year
- general knowledge of UPL tech
- enforcing Code of Conduct and any other rules
- something about soda :tropical_drink: ?

**Comment by katamaritaco** [comment]
Thanks for those Leo. How does it look now?

**Comment by LOZORD** [comment]
LGTM :+1: We can close this (and #39) at the meeting later this month.
