### ISSUE TITLE
Make Library/contents not "View Only"; add Grey Hat Hacking to the library too

### ISSUE THREAD

**Issue by WowSuchRicky** [UW-UPL/Documentation#35]
Make Library/contents google doc sheet not View Only, also add Grey Hat Hacking 3e

**Comment by LOZORD** [comment]
What is the motivation for changing from View Only? I think this should be editable through the Google account only (or otherwise individual coord accounts).

**Comment by katamaritaco** [comment]
I agree that it shouldn't be editable to all - only to the coord google account, since we only add books infrequently.

**Comment by LOZORD** [comment]
I can take care of _Grey Hat_ tomorrow.

**Comment by LOZORD** [comment]
Added _Gray Hat_, not going to make library editable for public
