### ISSUE TITLE
Figure out DNS propagation changes needed for new website, instead of 301 Redirect

### ISSUE THREAD

**Issue by WowSuchRicky** [UW-UPL/Documentation#38]
Not exactly sure what we need to do here. We only own/host an RDNS (Reverse-DNS) rather than a DNS entirely from what I know, so we may need to reach out to CSL/Parter about this.

**Comment by WowSuchRicky** [comment]
This will break home folders, because they also point to upl.cs.wisc.edu...... this is on hold for now.

**Comment by katamaritaco** [comment]
Why'd you mark blocked AND closed?

**Comment by WowSuchRicky** [comment]
There isn't a fix that we know of, nor is it super necessary. Unless other people think there is, then we can keep trying.
