### ISSUE TITLE
Add New Coord Applications here.

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/Documentation#39]

**Comment by katamaritaco** [comment]
I was thinking we make a nice .md

**Comment by LOZORD** [comment]
Would it just be a list of questions? Not necessarily a "form"?

**Comment by katamaritaco** [comment]
Yeah that is what I was thinking. Just something we can have up here, edit when we need to, and then easily throw in a form when the time comes

**Comment by LOZORD** [comment]
Sure, I can take care of this. I'll let you know when the draft is ready for review.

**Comment by LOZORD** [comment]
This depends on #32 .

**Comment by LOZORD** [comment]
See #42 for the draft

**Comment by katamaritaco** [comment]
Draft looks nice @LOZORD. I'll work on this document soon

**Comment by LOZORD** [comment]
We can close this at the Leap Day meeting. I added the issue on the FB event.
