### ISSUE TITLE
Add documentation for Pepade Machine

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/Documentation#4]

**Comment by katamaritaco** [comment]
@MikeCook9994 Do you want to take charge on this?

**Comment by MikeCook9994** [comment]
Would this be the arcade computer? Or the windows machine? Either way I can do it.

**Comment by katamaritaco** [comment]
Arcade computer. :)

Get Outlook for Androidhttp://aka.ms/ghei36

On Sun, Feb 7, 2016 at 8:05 AM -0800, "Michael Cook" <notifications@github.com<mailto:notifications@github.com>> wrote:

Would this be the arcade computer? Or the windows machine? Either way I can do it.

##

**Comment by MikeCook9994** [comment]
Absolutely. I'll be documenting what I know and documenting as I learn.

**Comment by WowSuchRicky** [comment]
So, this apparently broke a week ago and new coords have taken it over with a new OS and whatnot. @bhans117  and others, any update on docs? Even just linking to the docs of the OS itself would be a good help.

**Comment by LOZORD** [comment]
So we dropped the Lakka OS and are using something else?

**Comment by LOZORD** [comment]
@bhans117 be sure to update any necessary info in the `README`.

**Comment by WowSuchRicky** [comment]
@bhans117  @MikeCook9994  or @UW-UPL/coords  anything new with this?

**Comment by LOZORD** [comment]
Do we want to add anything about the user accounts on here?

**Comment by katamaritaco** [comment]
john looking at it

**Comment by LOZORD** [comment]
Is 🐸  💀 ? 🐫

**Comment by LOZORD** [comment]
@jdetter any update?

**Comment by jdetter** [comment]
I will have to reinstall the retro arch stuff and do proper documentation, I probably won't be able to get to this for at least a week or two. I will get it done though! Thanks for the reminder Leo =D
