### ISSUE TITLE
Go through current main README; Edit for new changes.

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/Documentation#41]
We went through a large purge and did a shit ton of work for the UPL recently. We'll want to make sure the main readme here is up to date and doesn't become stale.

**Comment by katamaritaco** [comment]
I'm going to assign @jdetter because he has been doing the most in this area, but everyone that knows a bit should help out

**Comment by LOZORD** [comment]
Completed #48 for change from janky Python + Psql :arrow_right: `upl-admin`

**Comment by WowSuchRicky** [comment]
I think we've done almost all of this. Re-open if there's anything noticed missing.
