### ISSUE TITLE
Screw the broken power jack properly into the wall

### ISSUE THREAD

**Issue by MikeCook9994** [UW-UPL/Documentation#44]
There's a power jack near the junk pile that is broken and electrical taped and not screwed in. Should be fixed.

**Comment by LOZORD** [comment]
I'm on it. I will email the building manager about it, as well as the whiteboard.

**Comment by LOZORD** [comment]
See Roger's response.

**Comment by WowSuchRicky** [comment]
- I think the facilities management dude just came and did this so we should be good to keep closed

**Comment by LOZORD** [comment]
Yup, LGTM :+1: 
I also notified Roger about the whiteboard.
