### ISSUE TITLE
New User Form should be at most one page long

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/Documentation#45]
Most people will not check w/e is on the back, also @MikeCook9994 thinks it's crufty.

**Comment by katamaritaco** [comment]
Sure, but the back is just signature. Go ahead and make it one page without removing content. glhf :+1:

**Comment by katamaritaco** [comment]
If somebody isn't going to sign up for this soon, I'll cruft.

**Comment by LOZORD** [comment]
It's just the coord signature on the back, right? If that's it, feel free to cruft.

**Comment by katamaritaco** [comment]
Yeah that is it. crufting.
