### ISSUE TITLE
Remove all the add coord and remove coord SQL documentation once John's script works perfectly, and is verified

### ISSUE THREAD

**Issue by WowSuchRicky** [UW-UPL/Documentation#47]
Remove all the add coord and remove coord SQL documentation once John's script works perfectly, and is verified. 

Assigning @LOZORD  for now, feel free to reassign accordingly.

**Comment by LOZORD** [comment]
Fine with me. Just keep me in the loop @jdetter

**Comment by jdetter** [comment]
not `sudo bash upl-admin`, just `sudo upl-admin`. Other than that, looks great! It would be awesome if we could do all of the CSL/UPL bit and mailing list stuff in code somehow. I will try to get it to work at some point.

**Comment by WowSuchRicky** [comment]
To do that, we would need to (programmatically):

-Login to CSL (www-auth.cs.wisc.edu) as upluse
-POST to /forms/upl.cgi

here's a traced POST (cookie removed for... reasons)

> POST /forms/upl.cgi HTTP/1.1
> Host: www-auth.cs.wisc.edu
> Connection: keep-alive
> Content-Length: 28
> Cache-Control: max-age=0
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,_/_;q=0.8
> Origin: https://www-auth.cs.wisc.edu
> Upgrade-Insecure-Requests: 1
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
> Content-Type: application/x-www-form-urlencoded
> DNT: 1
> Referer: https://www-auth.cs.wisc.edu/forms/upl.cgi
> Accept-Encoding: gzip, deflate
> Accept-Language: en-US,en;q=0.8
> Cookie:

**Comment by LOZORD** [comment]
I just put `DEPRECATED` warnings in all of the Python files in the `bin` directory.

I'm going to export all the Postgres DB data and then drop the tables.

**Comment by LOZORD** [comment]
I tried to dump the database, but it doesn't seem to be up anymore:

```
root@eris:/# psql
psql: could not connect to server: No such file or directory
    Is the server running locally and accepting
    connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.<redacted>"?
root@eris:/# 
```

Any advice? Can we close this now?

**Comment by LOZORD** [comment]
@Ricky54326 @jdetter do you think the new package management system removed any necessary Postgres stuff?
