### ISSUE TITLE
Update README to reflect move to Docker

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/Documentation#49]
Remove any `cf*` stuff

**Comment by WowSuchRicky** [comment]
@jdetter  can you let me know where the config files are actually being read from for DNS? I can update the docs, but need this info.

**Comment by WowSuchRicky** [comment]
This should be done now, see https://github.com/UW-UPL/UPL-Config/issues/29 (as this is somewhat a joint-repo thing)
