### ISSUE TITLE
What ALL coords need to know about sysadmining the lab

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/Documentation#50]

**Comment by LOZORD** [comment]
:camel:

**Comment by katamaritaco** [comment]
:camel: Might be good to have this done over Summer so that it'll be good to go once semester starts @Ricky54326

**Comment by LOZORD** [comment]
🐫

**Comment by LOZORD** [comment]
@Ricky54326 are you free to work on this now?

**Comment by WowSuchRicky** [comment]
We're going to close this for now, and keep docs more and more updated and less dependent on tribal knowledge.
