### ISSUE TITLE
Make "start of semester" checklist

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/Documentation#51]
What needs to be done at the first meeting of every semester

**Comment by katamaritaco** [comment]
working on it:
https://github.com/UW-UPL/Documentation/blob/master/Start-Of-Semester-Checklist.md

**Comment by LOZORD** [comment]
I made a big update: https://github.com/UW-UPL/Documentation/commit/4c113ec8134c0d4c5dc6a11d030eb41e120eaa59

**Comment by WowSuchRicky** [comment]
https://github.com/UW-UPL/Documentation/commit/94a5fd60fa0c9867573cf029609d6e86dc32a29c also. Should be done.
