### ISSUE TITLE
Script to automate updating pianobar config file.

### ISSUE THREAD

**Issue by spwilson2** [UW-UPL/Documentation#52]
I know we have the 'solution' in the readme, I think it'll be easier just to add a script to save time.

It should be pretty simple to add - I'll work on it at some point.. Probably this weekend.

```
openssl s_client -connect tuner.pandora.com:443 < /dev/null 2> /dev/null | \
    openssl x509 -noout -fingerprint | tr -d ':' | cut -d'=' -f2
```

And direct this into the user's `$HOME/.config/pianobar/config`.

**Comment by WowSuchRicky** [comment]
Any luck?

**Comment by spwilson2** [comment]
My bad, forgot about this. I'll mark my calendar to do it next weekend
unless anyone wants to.

**Comment by spwilson2** [comment]
Commited to UPL-Config/upl-scripts/user/fix-pianobar

@jdetter  @Ricky54326  Could get this added to user's aliases or bin dir? Feel free to change the name as well.

**Comment by LOZORD** [comment]
🐫

**Comment by spwilson2** [comment]
Pretty sure I opened a separate issue asking how to get this script to
users, I'll check later to see if I did and assign it to Jammie or Ricky

**Comment by spwilson2** [comment]
See discussion in [UW-UPL/UPL-Config](https://github.com/UW-UPL/UPL-Config/issues/37) for progress. Documentation on this script will be added once it is available to users.
