### ISSUE TITLE
Create Prospective Student/Building Tour Guide

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/Documentation#53]

**Comment by katamaritaco** [comment]
I can definitely help on this since I've given more tours than I can count

**Comment by LOZORD** [comment]
Awesome :ok_hand: I will start this tomorrow during my hour

**Comment by LOZORD** [comment]
Started work: https://github.com/UW-UPL/Documentation/commit/9a4cc8544e2e66162eee6fa426fade9160ed2b00

**Comment by LOZORD** [comment]
@katamaritaco what do you think? Can we close now?

**Comment by katamaritaco** [comment]
I'll look at and close
