### ISSUE TITLE
/webcam/webcam.sh doesn't exist like /etc/rc.local expects it to

### ISSUE THREAD

**Issue by spwilson2** [UW-UPL/Documentation#55]
From the docs 

> Webcam stream
> Runs out of /webcam folder on eris
> Started by a line in /etc/rc.local on eris
> These changes to rc.local should be moved so that cfengine enforces them, but I’m lazy

I was unable to restart the webcam to fix this @Ricky54326 know the actual procedure now?

**Comment by WowSuchRicky** [comment]
I will look into this ASAP. It's been hella wonky lately.

Sent from my iPhone

On Apr 22, 2016, at 6:41 PM, Sean Wilson <notifications@github.com<mailto:notifications@github.com>> wrote:

Assigned #55https://github.com/UW-UPL/Documentation/issues/55 to @Ricky54326https://github.com/Ricky54326.

##

**Comment by LOZORD** [comment]
🐫 ?
