### ISSUE TITLE
How to ssh into the UPL workstations?

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/Documentation#58]
I get a MITM warning whenever I attempt to `ssh` into the workstation machines.

**Comment by spwilson2** [comment]
Is it just from changed keys Leo? @Ricky54326 @jdetter did the sshd keys change when we reworked the lab?

**Comment by WowSuchRicky** [comment]
Remove your ~/.ssh/known_hosts file. Sometimes it gets corrupted and needs to be re generated.

Sent from my iPhone

On May 14, 2016, at 12:33 PM, Sean Wilson <notifications@github.com<mailto:notifications@github.com>> wrote:

Is it just from changed keys Leo? @Ricky54326https://github.com/Ricky54326 @jdetterhttps://github.com/jdetter did the sshd keys change when we reworked the lab?

##

**Comment by LOZORD** [comment]
Thanks! WFM. I will add a note to the README.
