### ISSUE TITLE
Add content to Start of Semester list

### ISSUE THREAD

**Issue by LOZORD** [UW-UPL/Documentation#59]
Be sure to:
- update the website with
  - new coords (and remove old coords)
  - new hours
  - any new events
- make sure there is a "maintainer" for each "project"; examples:
  - Security
  - Website
  - Lab machines/upl-config
  - Equipment

**Comment by LOZORD** [comment]
This script should also be ran to see any remaining issues:

https://gist.github.com/LOZORD/3dd6c549d564816693e3cb00dfdaf261

**Comment by jdetter** [comment]
Revisiting at the next meeting

**Comment by katamaritaco** [comment]
Was this revisited? 🐫

**Comment by spwilson2** [comment]
Closing. As far as creating maintaners, it's not set yet. We'll deal with something like that when we talk about @Ricky54326's [proposals](https://docs.google.com/document/d/1M8K9me2RwIWnaCjasGHTbdOliCWP3aBDy9EzXewGCX4/edit).
