### ISSUE TITLE
Fix User Websites not being served correctly.

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/Documentation#6]
UPL has hosted user websites in the past, and it currently isn't working correctly.

**Comment by LOZORD** [comment]
How is this different than the `~/public/html` directory given by the CS department?

**Comment by WowSuchRicky** [comment]
It's not, except that users would have it "forever" even after they graduate and whatnot. Either way if it's a feature that was working at some point maybe it's worth fixing.

**Comment by LOZORD** [comment]
Would CSL have to handle this?

**Comment by daguava** [comment]
No, we serve them, and its broke due to some Linux permission issue I believe.

**Comment by WowSuchRicky** [comment]
Fixed, I hope?

/etc/apache2/mods-enabled/userdir.conf had:

`<Directory /home/*/public_html>`

Was supposed to be:

`<Directory /home/*/*/public_html>`

My home directory now serves at ~/public_html

**Comment by LOZORD** [comment]
There's still a [line](https://github.com/UW-UPL/Documentation#apache-webserver) about this in the README. Ok to remove?

**Comment by katamaritaco** [comment]
If it is fixed, I'd def edit the readme
