### ISSUE TITLE
Add New User Form to GH

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/Documentation#7]
Writing in Markup and storing on here would be :+1: :100:

**Comment by katamaritaco** [comment]
Writing in Markup and storing on here would be :+1: :100:

**Comment by LOZORD** [comment]
Closed by 2254b99

**Comment by katamaritaco** [comment]
I'mma Write in Markup and storing on here would be :+1: :100: for maintainability

**Comment by LOZORD** [comment]
I'll make a new issue

**Comment by LOZORD** [comment]
See #10
