### ISSUE TITLE
Create Physical Repo in room of documentation when this is solid

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/Documentation#8]
Nick is working on this

**Comment by katamaritaco** [comment]
Will be doing this following UPL Hack, when stuff will most likely change and I can use @Ricky54326 's free prints :+1:

**Comment by katamaritaco** [comment]
This is still a little in flux since a lot of changes still happening....

**Comment by LOZORD** [comment]
:camel:

**Comment by katamaritaco** [comment]
Think it'd be good now, but I don't have any prints... @jdetter do you have unlimited prints left?

**Comment by LOZORD** [comment]
🐫

**Comment by katamaritaco** [comment]
Somebody with free prints will have to do this... @Ricky54326  @jdetter  @spwilson2

**Comment by spwilson2** [comment]
Yeah, I'd like to wait a bit more I know we have at least something still
on @Ricky54326.

**Comment by jdetter** [comment]
I still have unlimited prints, I could do this when I get back from Cali.

**Comment by LOZORD** [comment]
@jdetter are you free to do this now?

**Comment by jdetter** [comment]
I could do this on Monday, I was out of town in Milwaukee all weekend so I wasn't here

**Comment by WowSuchRicky** [comment]
Labeling as cruft and closing for now, docs update way too much to have any of this in paper.
