### ISSUE TITLE
Add Code of Conduct here.

### ISSUE THREAD

**Issue by katamaritaco** [UW-UPL/Documentation#9]

**Comment by LOZORD** [comment]
What do you think about forking http://hackcodeofconduct.org/?

**Comment by LOZORD** [comment]
Ok, I put a **draft** version up. @katamaritaco @melutzke @marshmue what do you think?

**Comment by katamaritaco** [comment]
It looks nice to me. @melutzke  @MarshMue what do you think? I'm thinking we should talk about this at next coord meeting and then solidify :100: 

Note for others: The 'account policy' at the bottom is from the previous account policy.
We'll need to link to this doc in the new website and reflect that change on the new user sheet

**Comment by WowSuchRicky** [comment]
This is done now / split into other issues right? If not, re-open.
